apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopsdemo
spec:
  selector:
    matchLabels:
      app: devopsdemo
  replicas: 2
  template:
    metadata:
      labels:
        app: devopsdemo
    spec:
      containers:
      - name: devopsdemo-container
        image: lbgeorgiev.jfrog.io/docker/devopsdemo:8882a727b5eec0dad1b82f61f8b3a6845916d53e
      imagePullSecrets:
      - name: artifactorycred
---
apiVersion: v1
kind: Service
metadata:
  name: devopsdemo-service
spec:
  selector:
    app: devopsdemo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
